# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class A365 < Formula
  desc "CLI for Microsoft 365 via agent365 MCP servers"
  homepage "https://github.com/sozercan/a365cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sozercan/a365cli/releases/download/v0.3.0/a365_0.3.0_darwin_amd64.tar.gz"
      sha256 "a6842347db431272c29cca51e7cc51cfbcb93d068280827cfc7ecd175fbd5a3f"

      define_method(:install) do
        bin.install "a365"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sozercan/a365cli/releases/download/v0.3.0/a365_0.3.0_darwin_arm64.tar.gz"
      sha256 "98813918d847dc6a7b37efccec60548532add30fe7f35469f00f3660e7f69cb3"

      define_method(:install) do
        bin.install "a365"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sozercan/a365cli/releases/download/v0.3.0/a365_0.3.0_linux_amd64.tar.gz"
      sha256 "2caaf7fbc9b135693aef766725765473c0a29e15f0e0909c1e40863114409eb7"
      define_method(:install) do
        bin.install "a365"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sozercan/a365cli/releases/download/v0.3.0/a365_0.3.0_linux_arm64.tar.gz"
      sha256 "83b2c2ae3fbed57fee01efdb7be4210a37797af8d2db848dc11715af427257c2"
      define_method(:install) do
        bin.install "a365"
      end
    end
  end

  test do
    system "#{bin}/a365", "--version"
  end
end
